module:
  imports:
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-sass-utilities
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-sass-typography
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-utility-partials
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-mod-header
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-mod-footer
  - disable: false
    ignoreConfig: true
    path: github.com/bugoio/bugo-font-awesome
  - disable: false
    ignoreConfig: true
    path: github.com/bugoio/bugo-mod-breadcrumbs
  - disable: false
    ignoreConfig: true
    path: github.com/bugoio/bugo-mod-article
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-mod-share
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-mod-search
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-mod-navigation